name: S3 Upload and Update Repo

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  s3_upload:
    name: Upload to S3 and Update Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - name: Upload to S3
        run: aws s3 sync dist s3://prod-pwc-frontend-bucket --delete

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: "ENE2OS119HR9L"
          PATHS: "/*"
          AWS_REGION: "ap-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
